/* Copyright (C) 2011-2020 Zeex
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */






























[callback] bool OnGameModeInit();
[callback] bool OnGameModeExit();
[callback, badret(false)] bool OnPlayerConnect(int playerid);
[callback, badret(false)] bool OnPlayerDisconnect(int playerid, int reason);
[callback, badret(false)] bool OnPlayerSpawn(int playerid);
[callback, badret(false)] bool OnPlayerDeath(int playerid, int killerid, int reason);
[callback, badret(false)] bool OnVehicleSpawn(int vehicleid);
[callback] bool OnVehicleDeath(int vehicleid, int killerid);
[callback, badret(false)] bool OnPlayerText(int playerid, string text);
[callback, badret(true)] bool OnPlayerCommandText(int playerid, string cmdtext);
[callback] bool OnPlayerRequestClass(int playerid, int classid);
[callback] bool OnPlayerEnterVehicle(int playerid, int vehicleid, bool ispassenger);
[callback] bool OnPlayerExitVehicle(int playerid, int vehicleid);
[callback] bool OnPlayerStateChange(int playerid, int newstate, int oldstate);
[callback] bool OnPlayerEnterCheckpoint(int playerid);
[callback] bool OnPlayerLeaveCheckpoint(int playerid);
[callback] bool OnPlayerEnterRaceCheckpoint(int playerid);
[callback] bool OnPlayerLeaveRaceCheckpoint(int playerid);
[callback, badret(true)] bool OnRconCommand(string cmd);
[callback, badret(false)] bool OnPlayerRequestSpawn(int playerid);
[callback] bool OnObjectMoved(int objectid);
[callback] bool OnPlayerObjectMoved(int playerid, int objectid);
[callback] bool OnPlayerPickUpPickup(int playerid, int pickupid);
[callback, badret(false)] bool OnVehicleMod(int playerid, int vehicleid, int componentid);
[callback] bool OnEnterExitModShop(int playerid, bool enterexit, int interiorid);
[callback, badret(false)] bool OnVehiclePaintjob(int playerid, int vehicleid, int paintjobid);
[callback, badret(false)] bool OnVehicleRespray(int playerid, int vehicleid, int color1, int color2);
[callback, badret(true)] bool OnVehicleDamageStatusUpdate(int vehicleid, int playerid);
[callback, badret(false)] bool OnUnoccupiedVehicleUpdate(int vehicleid, int playerid, int passenger_seat, float new_x, float new_y, float new_z, float vel_x, float vel_y, float vel_z);
[callback] bool OnPlayerSelectedMenuRow(int playerid, int row);
[callback] bool OnPlayerExitedMenu(int playerid);
[callback] bool OnPlayerInteriorChange(int playerid, int newinteriorid, int oldinteriorid);
[callback] bool OnPlayerKeyStateChange(int playerid, int newkeys, int oldkeys);
[callback] bool OnRconLoginAttempt(string ip, string password, bool success);
[callback, badret(false)] bool OnPlayerUpdate(int playerid);
[callback] bool OnPlayerStreamIn(int playerid, int forplayerid);
[callback] bool OnPlayerStreamOut(int playerid, int forplayerid);
[callback] bool OnVehicleStreamIn(int vehicleid, int forplayerid);
[callback] bool OnVehicleStreamOut(int vehicleid, int forplayerid);
[callback] bool OnActorStreamIn(int actorid, int forplayerid);
[callback] bool OnActorStreamOut(int actorid, int forplayerid);
[callback, badret(true)] bool OnDialogResponse(int playerid, int dialogid, int response, int listitem, string inputtext);
[callback, badret(true)] bool OnPlayerTakeDamage(int playerid, int issuerid, float amount, int weaponid, int bodypart);
[callback, badret(true)] bool OnPlayerGiveDamage(int playerid, int damagedid, float amount, int weaponid, int bodypart);
[callback, badret(true)] bool OnPlayerGiveDamageActor(int playerid, int damaged_actorid, float amount, int weaponid, int bodypart);
[callback, badret(true)] bool OnPlayerClickMap(int playerid, float fX, float fY, float fZ);
[callback, badret(true)] bool OnPlayerClickTextDraw(int playerid, int clickedid);
[callback, badret(true)] bool OnPlayerClickPlayerTextDraw(int playerid, int playertextid);
[callback, badret(true)] bool OnIncomingConnection(int playerid, string ip_address, int port);
[callback, badret(false)] bool OnTrailerUpdate(int playerid, int vehicleid);
[callback] bool OnVehicleSirenStateChange(int playerid, int vehicleid, int newstate);


[callback, badret(true)] bool OnPlayerClickPlayer(int playerid, int clickedplayerid, int source);


[callback, badret(true)] bool OnPlayerEditObject(int playerid, bool playerobject, int objectid, int response, float fX, float fY, float fZ, float fRotX, float fRotY, float fRotZ);
[callback, badret(true)] bool OnPlayerEditAttachedObject(int playerid, int response, int index, int modelid, int boneid, float fOffsetX, float fOffsetY, float fOffsetZ, float fRotX, float fRotY, float fRotZ, float fScaleX, float fScaleY, float fScaleZ);


[callback, badret(true)] bool OnPlayerSelectObject(int playerid, int type, int objectid, int modelid, float fX, float fY, float fZ);


[callback, badret(false)] bool OnPlayerWeaponShot(int playerid, int weaponid, int hittype, int hitid, float fX, float fY, float fZ);


[callback, badret(true)] bool OnPlayerRequestDownload(int playerid, int type, int crc);